### ISSUE TITLE
Best way to structure this repo

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#1]
I'm not entirely sure what the best way to set up a wordpress repo is. @darrell you had it originally set up to include everything from the root of the core wordpress files, but that seemed a bit too deep. 

Currently this is just the theme, but I can see including the `../plugins` directory would be a good idea if we decide to hook into your server for pushing updates live. Would remove a step for us on the wp-admin side in terms of installing plugins.

Thoughts?

**Comment by geografa** [comment]
depends if you want people updating core wordpress or not, seems. I don't know much about git submodules but we did something like that at the last Drupal shop I worked at. We never touched the core as that was updated periodically from WP. Are you going to setup a db and image dir we can use for test data? That might be something to consider as well.

**Comment by darrell** [comment]
Yah, I'd say the plugins and the theme files would be sufficient – no need to include the whole wordpress stack. The idea is that in case of disaster you have everything needed to re-build the site without necessarily falling on your backups – and wordpress itself is easily re-installed. 

git submodules only work if the thing you want it is in git somewhere, and I doubt that's true of all the wordpress plugins. I'd say don't try to use submodules for these purposes.

So I'd move the current files into a foss4g-theme subdirectory, then create a plugins subdirectory that we can copy the necessary files into.

I'll write a script that will check for updates and push them out as they come in.

**Comment by mapsam** [comment]
Test data would be a good idea, but for now I think we're good with the plugins and theme. I'm including the /uploads/ folder as well since it's only a few images but could be helpful if people need anything for testing. We may not necessarily want it to be part of the script that looks for changes, though. So ... let me know if I should just remove it. 

Also would people be interested in the /src folder within the theme itself? Of course they would! I just didn't want to grab all those unnecessary node_modules. 

Going to consider this our relatively, kind-of-permanent structure for the development process.
