### ISSUE TITLE
nav bar logo

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#14]
what logo do we want on the nav bar? I'm not a total fan of the current "compressed" version of the logo? Maybe we could just do the bird, or the foss ribbon?

**Comment by darrell** [comment]
I kind of like the bird.

d.

**Comment by mapsam** [comment]
MOAR BIRD

**Comment by mattsayler** [comment]
I hear the bird is the word.
I kind of like the bird.

d.

On Feb 17, 2014, at 10:52, Sam Matthews notifications@github.com wrote:

> what logo do we want on the nav bar? I'm not a total fan of the current
> "compressed" version of the logo? Maybe we could just do the bird, or the
> foss ribbon?
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/pdxosgeo/foss4g2014-wordpress/issues/14#issuecomment-35312561
.
