### ISSUE TITLE
contact form mysteriously appearing

### ISSUE THREAD

**Issue by darrell** [pdxosgeo/foss4g2014-wordpress#15]
Not sure why the contact form is on the bottom of this page: https://2014.foss4g.org/sponsor-foss4g/call-for-sponsors/

I can't see where it's coming from... kinda confused...

**Comment by mapsam** [comment]
Ha, nice. I've totally seen that form and didn't read it enough to realize it was the same one. Forms can be populated in a couple ways (typical wordpress) - one of which is by appending a form on the end of a post/page with the meta box that comes with the plugin (see screenshot). I removed the contact form!

![screen shot 2014-02-19 at 5 11 44 pm](https://f.cloud.github.com/assets/1943001/2214232/3bb9325a-99cd-11e3-8a9e-56fa4075d28f.png)
