### ISSUE TITLE
Get our website posts aggregated on http://planet.osgeo.org/

### ISSUE THREAD

**Issue by elil** [pdxosgeo/foss4g2014-wordpress#21]
Planet OSGeo would be a great place to have our posts show up.  Directions are here, http://wiki.osgeo.org/wiki/PlanetOSGeo

I think that it is a good idea to not break the planet formatting and to not repeatedly flood it with old posts.  I've seen these occasionally happen.  

While we are on planet, we should get this updated, 
"Join us for the FOSS4G 2013 conference, in Nottingham, UK."

**Comment by darrell** [comment]
Yes, do it.

Feed is https://2014.foss4g.org/feed/

**Comment by mapsam** [comment]
Hm, seems we've got an XML parsing error. This is likely due to blank space in any of the functions.php files - I'll do some cleaning!

![screen shot 2014-03-08 at 7 53 49 am](https://f.cloud.github.com/assets/1943001/2365730/ea76dcc0-a6d9-11e3-908e-c49b327b5c0d.png)

**Comment by darrell** [comment]
The feed validates at: http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F2014.foss4g.org%2Ffeed%2F

@elil Do you want to try it again on the planet feed?

**Comment by elil** [comment]
We are on, https://trac.osgeo.org/osgeo/changeset/11390 will check after next post
