### ISSUE TITLE
Post titles are disappearing

### ISSUE THREAD

**Issue by darrell** [pdxosgeo/foss4g2014-wordpress#22]
Looks like the CSS changed and now our titles are wonky:
![https___2014_foss4g_org__p_508_preview_true](https://f.cloud.github.com/assets/11126/2528884/552edd0e-b514-11e3-847f-d490c91b0e92.jpg)

**Comment by mapsam** [comment]
doh! This is totally my fault for not finishing my attempt to structure the pages a little more. Will add a temporary fix and plan on pushing through a few more content styles in the next couple days. Sorry!
