### ISSUE TITLE
links done broke

### ISSUE THREAD

**Issue by darrell** [pdxosgeo/foss4g2014-wordpress#23]
Links in pages or posts seem to have stopped working. They're highlighted, but actually clicking on them does nothing. Inspect element shows a link being there, but... side bar and navigation works fine, it's only links embedded in a post/page's content that are failing.

**Comment by mapsam** [comment]
I bet this is due to some z-index that I set so I could make that sidebar merge into the content space nicely - I'll do some tweaking!
