### ISSUE TITLE
Make it easier to access older blog post archives

### ISSUE THREAD

**Issue by elil** [pdxosgeo/foss4g2014-wordpress#27]
Right now it is difficult to access older blog post archives.  The recent posts lists the most recent five but older ones are impossible to find other than search (for instance, try to find the logo unveil post).

**Comment by mapsam** [comment]
I'm going to make a standard `archive.php` page here that will allow us to have the "monthly" archives. Additionally I think I'll just get the `blog.php` page looping through all of the posts to list them out and that can have date-based organization as well.

**Comment by mapsam** [comment]
Since we'll be having new author pages, do we want an author template as well?

**Comment by elil** [comment]
Archives and author templates would rock!

**Comment by mapsam** [comment]
archives ([example for may posts](https://2014.foss4g.org/2014/05/)) are there and author pages exist, but could use some love if we plan on using author descriptions and other built-in links.

**Comment by mapsam** [comment]
Also added [news](https://2014.foss4g.org/news/) page if you want to link it anywhere

**Comment by elil** [comment]
@svmatthews I missed this somehow, thanks.  
@darrell can we add the [news](https://2014.foss4g.org/news/) section to the main page?

**Comment by darrell** [comment]
I assume you mean a link to it yes?

**Comment by elil** [comment]
yes a link.

**Comment by darrell** [comment]
resolved in 65dad64dd7b6a20b3b951cd713240543b9c6c968.
