### ISSUE TITLE
add more POIs to map via foss4g2014-tourguide repo

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#28]
The homepage map can now take on multiple POIs for people to add to the map via the `geojson` variable in the `main.js` file. Need to add a few more style as we get a more diverse set of points, but that can come once we actually have them.

**Comment by mapsam** [comment]
Could we add restaurants and/or watering holes? Or is that getting too particular and subjective?

**Comment by darrell** [comment]
There’s a group that’s starting to write up that stuff. See the foss4g2014-tourguide repo.

Let’s wait for them to be ready, and then we can put that map on the appropriate page. Sound good?

**Comment by mapsam** [comment]
Sounds perfect!

**Comment by elil** [comment]
I'm not sure of the progress on this, but here are restaurants, https://github.com/pdxosgeo/foss4g2014-tourguide/blob/master/spatialdata/PortlandRestaurants.geojson

**Comment by alexatodd** [comment]
I just updated the restaurants...I think I had them saved in the wrong
folder. (sorry new to GitHub)

**Comment by elil** [comment]
Does the Icon file have illegal (on windows) characters in the name or extension?  I'm having a little trouble with it.

**Comment by elil** [comment]
Restaurants.geojson might not be in WGS 84.  If you have GDAL/OGR around, you can reproject it like: ogr2ogr -t_srs EPSG:4326 -f geojson -lco COORDINATE_PRECISION=5 Restaurants_output_name.geojson input_file

**Comment by alexatodd** [comment]
I saved the shapefile as a GeoJSON again. Hopefully this time it worked.

**Comment by alexatodd** [comment]
The dataset is in NAD84. I don't know how to re-project using QGIS. I'll
bring my computer to MapTime tomorrow and see if someone can help me.

:-)

**Comment by twelch** [comment]
@alexatodd In QGIS I think you can right click the data layer, save as, select geographic coordinate system WGS 84.

**Comment by elil** [comment]
To export to geojson from QGIS and reproject, you can right click the layer, choose "save as" and then fill out the screen like this:  
![geojson_export](https://cloud.githubusercontent.com/assets/5263258/3807039/2df30166-1c5c-11e4-92ea-b7cbe561707a.png)

Note the "Selected CRS" and "WGS 84" (found through "browse" and then typing "4326" in "filter" - if you know EPSG:4326 is WGS 84 it helps)

QGIS is actually using the OGR command too, QGIS is just a little more friendly about it.  

To check the coordinates/projection of the geojson file, any text editor will do.  Look for the coordinate in the geometry section:
![geojson_text](https://cloud.githubusercontent.com/assets/5263258/3807058/c460ce30-1c5c-11e4-8d1e-355d067cecfe.png)

**Comment by darrell** [comment]
Is the difference between nad83 and wgs84 meaningful at the scale?

On Aug 4, 2014, at 21:56, Tim Welch notifications@github.com wrote:

@alexatodd https://github.com/alexatodd In QGIS I think you can right
click the data layer, save as, select geographic coordinate system WGS 84.

**Comment by elil** [comment]
You can also delete the original geojson file and then save with the same name.  Then git and github will track the revisions (instead of more files).

**Comment by elil** [comment]
darrell: It is not datum (probably doesn't matter).  It is state plane vs. geographic.

**Comment by darrell** [comment]
Oh, carry on.

On Aug 4, 2014, at 22:00, Eli L Adam notifications@github.com wrote:

darrell: It is not datum (probably doesn't matter). It is state plane vs.
geographic.

**Comment by alexatodd** [comment]
Thanks, all! I think I got it this time. Didn't realize it was that easy!

**Comment by geografa** [comment]
Hey all, out of the loop but where does [this](https://github.com/pdxosgeo/foss4g2014-tourguide) stand? I've got a map started [here](https://a.tiles.mapbox.com/v4/grafa.j88kd98g/page.html?access_token=pk.eyJ1IjoiZ3JhZmEiLCJhIjoiU2U2QnIzUSJ9.4LnG05Ptvi1sUQ8t68rfgw#17/45.52802/-122.66291) we can just drop this onto the map or make a source with Mapbox Studio. Do we really need all those restaurants or can this be whittled down? /cc @elil @alexatodd @darrell

**Comment by twelch** [comment]
I'm out of the loop too but would like to be a part of the loop.

+1 to whittling and refining the POI's.

What would Mapbox Studio buy us at this point Rafa?  Styling surely.  Can
we create and manage a point layer with it like dd/edit/remove points?
 Thanks.

Restaurants are cool.  I had a thought to create a "Keep Portland Weird"
category fun quirky things that people would enjoy checking out in and
around the venues.

**Comment by elil** [comment]
I'm not in the loop either.  If @geografa and @twelch want to run with it that is fine by me.  

@geografa I love the birds on the map!  We can consider birds (smaller birds?) at the Eliot Center (code sprint), WFC (Gala night), Ecotrust (opening party)... other?  

@twelch I would also like to add other iconic points of interest (Powell's, Voodoo, etc)

**Comment by tchaddad** [comment]
haha - what Eli said. 

Very cute.

**Comment by mattsayler** [comment]
I think the loop collapsed when it became clear the map Darrell wanted made
was for the printed program, not the website. That led to figuring out the
dimensions were too small to include anything more than essential info.

BUT, I think an upgrade to the map is still on the wishlist, and Rafa has
made a good start. +1 for Rafa and Tim going to town.

Personally, I think we should adjust the max dimensions of the map on the
homepage too. It's not very tall on a wide screen monitor.

**Comment by darrell** [comment]
It can be on the website, too. Just pointed out that we needed a print version.

The map code can be changed here: https://github.com/pdxosgeo/foss4g2014-wordpress/blob/master/themes/foss4g-theme/js/home-map.js

**Comment by twelch** [comment]
I like the simplicity of the home page map being focused on the few main
venues.  Perhaps we can link to an expanded points of interest map a la
what Rafa has started.

**Comment by geografa** [comment]
@twelch agree. That map works great. Let's link off to another map and iframe it into another page. Keep it simple.

**Comment by mattsayler** [comment]
Yeah, a separate page works. It's just that I'd rather shove it in peoples'
faces cuz it's gonna be awesome. :-)

**Comment by geografa** [comment]
@mattsayler link to FULL MAP will be prominent :)

**Comment by geografa** [comment]
@twelch you want to handle wrangling the GeoJSON and I'll tidy up the base map? We just need categories to map on - lat,long, name, category, other? The rest we can do with JavaScript and some custom icon wizardry. We can use something like the [Store Locator](https://www.mapbox.com/foundations/building-a-store-locator/). 

And we can worry about print last - Mapbox Studio exports hi-res now (600ppi). @darrell do you have dimensions for the final map on the brochure?

**Comment by darrell** [comment]
We’ve already had someone working on the print map. Checkout the archives.

d.

**Comment by twelch** [comment]
Would be great to crowdsource the locations.  what do folks think about
using the Mapbox add-on for Google Docs?

https://www.mapbox.com/blog/mapping-google-doc-spreadsheet/

**Comment by geografa** [comment]
Sorry, only issue I see is this: https://github.com/pdxosgeo/foss4g2014-wordpress/issues/33 /cc @svmatthews

**Comment by mattsayler** [comment]
Go for it.

**Comment by twelch** [comment]
@geografa I think he meant the email archives.  A series of 3 maps created using QGIS and Inkscape is being finalized.

**Comment by geografa** [comment]
Awesome.

On Wednesday, August 20, 2014, Tim Welch notifications@github.com wrote:

> @geografa https://github.com/geografa I think he meant the email
> archives. A series of 3 maps created using QGIS and Inkscape is being
> finalized.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pdxosgeo/foss4g2014-wordpress/issues/28#issuecomment-52833933
> .

## 

Rafa Gutierrez
support@mapbox.com

**Comment by geografa** [comment]
@twelch time tonight to hack on this? Getting close to final basemap with main POIs https://a.tiles.mapbox.com/v4/grafa.jdib780o/page.html?access_token=pk.eyJ1IjoiZ3JhZmEiLCJhIjoiU2U2QnIzUSJ9.4LnG05Ptvi1sUQ8t68rfgw#14/45.5183/-122.6634 We can do the Foursquare POI thing or make our own.

**Comment by twelch** [comment]
Energy has shifted to this new map (https://github.com/pdxosgeo/foss4g-map).  It's plugged in as a 'View More' link on the main POI map on the FOSS4G home page.  It's a combination of Jason Sanford's map setup with @geografa's base map.

People should add more interesting POI's.
