### ISSUE TITLE
contact form messes up links

### ISSUE THREAD

**Issue by darrell** [pdxosgeo/foss4g2014-wordpress#3]
See: http://foss4g.renewfund.com/sponsorships/

When the contact form is closed, any text (and links) that overlap the contacts form div as it would be when opened are inaccessible. 

Try clinking the links with the window resized so that the open contact form does/does not overlap the links to see what I'm getting at.

**Comment by mapsam** [comment]
I noticed this recently - something I'm trying to figure out on my end. Also ... seems like all of our <head> links are broken right now since no CSS styles are coming in

**Comment by mapsam** [comment]
Ah, looks like you're in the middle of changing the domain ;)

``` HTML
<link rel="stylesheet" type="text/css" href="http://2014.foss4g.org/wp-content/themes/foss4g-theme/style.css" />
```

**Comment by darrell** [comment]
Yes, sorry. I'm waiting for the DNS change to go through. Usually they're very fast about that sort of thing, but I wanted to be prepared.

Assuming you're on a mac, from a terminal you can do 'sudo nano /etc/hosts' and add a line:
216.151.2.221   2014.foss4g.org

that will make it all work until the DNS gets updated.

**Comment by darrell** [comment]
alternatively, feel free to change it back in the config. The old URL should work fine indefinitely.

**Comment by mapsam** [comment]
Alright, the footer 'contact' form now has a smaller set height when it's close and changes on click so it doesn't block text that the original container is overlapping. 

Darn relative positions!

**Comment by darrell** [comment]
Surely you've seen: https://www.dropbox.com/s/ern1z6ctejxo7ds/CSS.gif
