### ISSUE TITLE
Need to add a form for Map Gallery submissions.

### ISSUE THREAD

**Issue by tchaddad** [pdxosgeo/foss4g2014-wordpress#32]
We're working on the "Call for Maps" here:
https://docs.google.com/document/d/1i1uocjo-JSUjgtAFyWFiJcVXn46_5xtQ7uPwQlHtFu4/edit

As part of that we will need a web form for Map Gallery submissions. Info to be collected via the form includes:
- Name
- Organization
- Additional map authors
- Text Box for Statement on the map design and production process 
- Competition category (select 1 of 4 choices)
- Map format  (select 1 of 2 choices), plus input box for URL 
- Statement of original work / authenticity

**Comment by mapsam** [comment]
Alright, not too tough! Added some form plugin and built a test page. Things we'll need to know:
- anyone want the submission responses sent to them?
- the fields need to be fleshed out, and can be edited in the backed if you go to forms > map gallery > field settings
- what's the form type for "statement of original work?" - _textarea_?

Test page located at (https://2014.foss4g.org/gallery-submissions/)[https://2014.foss4g.org/gallery-submissions/] so you can check it out. Any parent page this should be associated to? Potentially under the "attending" section ...

**Comment by tchaddad** [comment]
Sweet! - just made some changes trying to learn whats possible & flesh things out a bit. 
- we should probably have an alias that gets the map submissions. I can be one of the recipients, but we will have others as well, need to work that out...
- the statement of original work is just something we want people to agree to (Nottingham had a disputed map). I've put in some placeholder text ahead of a submit button to give the general idea. I'll get some people to work on real text and what it should be called.
- for the parent page, it would seem to go under "call for papers", but I'll ask around...

**Comment by darrell** [comment]
We already have the WPUF plugin that we're using for all the other forms,
shouldn't we just keep using that?

On Jun 18, 2014, at 19:14, Sam Matthews notifications@github.com wrote:

Alright, not too tough! Added some form plugin and built a test page.
Things we'll need to know:
- anyone want the submission responses sent to them?
- the fields need to be fleshed out, and can be edited in the backed if
  you go to forms > map gallery > field settings
- what's the form type for "statement of original work?" - _textarea_?

**Comment by mapsam** [comment]
Probably - but sometimes the guy who set up the site forgets things :)

I'll recreate the form in WPUF and will remove ninja forms - thanks for taking a look @tchaddad !

**Comment by tchaddad** [comment]
Just checking in on this to see if the switch has been made? We'd like to get a press release out this week, and so the form should be in place when that goes out...

**Comment by mapsam** [comment]
@darrell do we need to add a new custom post type just to make a form?

**Comment by twelch** [comment]
Thanks for pushing this Tanya, a few suggestions after reviewing the form:
- Optional creative commons licenses for static maps?  Makes it more likely
  others will make use of the work.  The 'you can't use these maps for
  anything' message in the Nottingham gallery is a little off-putting.  I'm
  sure many wouldn't mind doing say a CC attribution no-deritatives license
  so other people can safely blog about it or put it into a powerpoint.
- Optional link to source code/data sources.
- Optional Twitter handle(s).  Allow people to connect with/follow the
  makers more easily.

**Comment by darrell** [comment]
I don’t think so, though it probably makes them more easy to access.

d.

**Comment by mapsam** [comment]
Just to clarify - are we making this form available for only logged in users or should this be public, sans login?

**Comment by tchaddad** [comment]
Open to Community submissions, so public, sans login.

Tim - thanks for the suggestions, as soon as the form is moved over, I'll work on adding some of the items you mention.

**Comment by darrell** [comment]
So, we’ve generally done this where we require people to get a login, ala the presentations submissions, so we know how to contact them.

Are we sure we want something different?

d.

**Comment by tchaddad** [comment]
Nope - I was just assuming you don't want barriers. No problem from me if you want to stick with the current pattern.

**Comment by mapsam** [comment]
If we don't need users, I'm going to recommend keeping the current ninja form then, since that compiles entries and we will have the required email field. Since there aren't any file uploads and there isn't a need to have the data accessible via wordpress queries (custom posts) this solution should stand strong.

**Comment by tchaddad** [comment]
Made some updates based on Tim's suggestions. Can't figure out how to remove the default text at the top of the form, so pointers there would be great.

**Comment by mapsam** [comment]
Are you talking about the "Content Here" text? That's just content in the page, unrelated to the form. I removed that and removed the default "fields with \* are required" so it's not duplicated with your text. How does the page look now?

**Comment by tchaddad** [comment]
Yes, thanks - that was it. I was looking in the wrong place. I'm going to add one more thing and then this will be good to go out (looks like early in the AM for the mailchimp blast).

**Comment by mapsam** [comment]
great! Would be good to associate the submissions page with other pages to fill in that sidebar on the left too. Who designed this thing?!

**Comment by twelch** [comment]
Done.
