### ISSUE TITLE
Map Gallery page

### ISSUE THREAD

**Issue by twelch** [pdxosgeo/foss4g2014-wordpress#37]
I'm planning to create a landing page for viewing the map gallery submissions and voting.  I think this should get a whole sub-section on the home page or at least a button (not buried under primary nav).  Any strong thoughts @svmatthews?

**Comment by darrell** [comment]
That’s fine.

Also @svmatthews is on vacation, so he probably won’t see this any time soon.

Go forth and make changes!

d.

**Comment by twelch** [comment]
Oh I thought he was on the recent thread, guess it was old replies.

My hurdle right now is I don't have a dev version of the Wordpress site in
place.  I need to work on that.

**Comment by darrell** [comment]
Let me know if you want a dump of the database.

d.

**Comment by twelch** [comment]
Just need to add to the homepage when we go live next week
