### ISSUE TITLE
Coordinate user roles and user "posts" for submissions and workshops

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#4]
Going to allow people to "guest post" when signed in - these posts will be categorized under specific types (i.e. talks, workshops) and presumably only viewable by admin since there will not be a template filtering for these post categories. 

Also - Wordpress needs a new word for "posts" ... maybe "item" would be more inclusive of what posts are used for.

**Comment by darrell** [comment]
Looking good!

**Comment by mapsam** [comment]
I'm going to close this one - doesn't seem like we've been running into an issue at all with the Wordpress User Frontend, eh? Woot!
