### ISSUE TITLE
Sponsor post type

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#5]
Create post type for "sponsors" so we can use "featured images" and push all over the website. We could even subcategorize these to show specific level sponsors in different places.

**Comment by mapsam** [comment]
Along with this - style the sponsor bar on the main page to be a set height (or use set height images) - so the block element doesn't change for every carousel switch. 

Another thought - do we want to remove color from all of the images so there isn't a huge cluster of color on the page?

**Comment by darrell** [comment]
Yah, I noticed the jumping height thing. Probably setting it to be fixed height is a good idea.

I'm not sure we'd be allowed to modify the sponsor logos, but I guess we could try it and see if anyone complains. ;)

**Comment by mapsam** [comment]
Created a custom post type "sponsors" to keep the admin side of things straightforward. Also specified a new taxonomy class "levels" so they are separate from other categories in posts. 

Want to ensure we can put an "order" to these taxonomies (i.e. platinum, gold, silver, etc.) but tough since they are no alphabetical or numeric. Thinking we may be able to sort by their ID as long as they are created in the correct order ...

``` PHP
$tax_args=array('orderby' => 't.term_id');
```

Will give this a try.

**Comment by darrell** [comment]
I'm not sure how flexible Wordpress is in doing custom queries, but I was thinking we could weight by sponsorship level and multiply that by rand(). That gives more prominence to bigger sponsors.

So, like:

``` sql
... ORDER BY rand() * 
  CASE level 
  WHEN 'Platinum' then log(7)
  WHEN 'Gold' then log(6)
  WHEN 'Silver' then log(5)
  WHEN 'Bronze' then log(4)
  WHEN 'Supporter' then log(3)
  WHEN 'Media' then log(2)
  ELSE 1 END
 LIMIT 5;
```

**Comment by mapsam** [comment]
Oh, great idea! Ya I figured we would change up how they are populated once we start getting more levels fleshed out. It's surprisingly difficult to add an "order" to taxonomy terms that are inherently qualitative. I'm thinking Platinum sponsors should probably show up every time, outside of that random loop - what do you say?

**Comment by darrell** [comment]
Yah, always featuring platinum sponsors is a good idea.
