### ISSUE TITLE
Style sidebar

### ISSUE THREAD

**Issue by mapsam** [pdxosgeo/foss4g2014-wordpress#6]
Or completely remove the sidebar because sidebars stink! But, style it for now.

**Comment by darrell** [comment]
You beat me to this suggestion. ;)

**Comment by mapsam** [comment]
Temporarily styled upon the public announcement :) Will probably change in a bit but want to work on some graphics for the homepage and headers now.

**Comment by mapsam** [comment]
Alright, I'm calling this one with all the new styles today.
