### ISSUE TITLE
Add 'More...' link to detailed POIs map

### ISSUE THREAD

**Issue by geografa** [pdxosgeo/foss4g2014-wordpress#61]
Based on [Jason Sanford's](https://github.com/JasonSanford/foss4g-map) work, can we add this map: http://pdxosgeo.github.io/foss4g-map/ as a more detailed view of the existing POI map?

**Comment by darrell** [comment]
as a link or as something else?

**Comment by twelch** [comment]
Yeah the idea was a link or button alongside or within the front page map to 'view more' or something like that.  Maybe top right header above the map.

**Comment by twelch** [comment]
I'll add the link.  Sprinkling it into a few other places as well such as https://2014.foss4g.org/attending/getting-to-portland/

**Comment by twelch** [comment]
Done.  Updated the conference POI's as well

**Comment by geografa** [comment]
:+1:
