### ISSUE TITLE
Add space for more explicit location info on front page (per feedback)

### ISSUE THREAD

**Issue by tchaddad** [pdxosgeo/foss4g2014-wordpress#8]
Probably the best space is in the "Conference Date Information" block, just underneath "Main Conference".

Suggest something like:

Location: Portland, Oregon, U.S.A
or
Join Us: Portland, Oregon, U.S.A.

**Comment by darrell** [comment]
Resolved in 5459a6ec72 and 7e328f4c8, but the styling could probably be better.
